apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: math2do/api-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "PROD"
